### ISSUE TITLE
不必现的报错

### ISSUE THREAD

**Issue by TopTime1** [ladingwu/dimens_sw#20]
java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.com.zwwl.bayuwen/cn.com.zwwl.bayuwen.activity.MainActivity}: android.view.InflateException: Binary XML file line #13: Binary XML file line #2: Error inflating class <unknown>
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3300)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
    at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5380)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5276)
    at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
   
Caused by: android.view.InflateException: Binary XML file line #13: Binary XML file line #2: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at android.view.LayoutInflater.createView(LayoutInflater.java:658)
    at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64)
    at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:105)
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:731)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:799)
    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:976)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
    at cn.com.zwwl.bayuwen.activity.MainActivity.onCreate(MainActivity.java:137)
    at android.app.Activity.performCreate(Activity.java:7436)
    at android.app.Activity.performCreate(Activity.java:7426)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
    at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5380)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5276)
    at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
    at android.os.Handler.dispatchMessage(Handler.java:109)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:7470)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 16 to dimension: type=0x1
    at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:783)
    at android.view.View.<init>(View.java:5068)
    at android.view.ViewGroup.<init>(ViewGroup.java:659)
    at android.widget.LinearLayout.<init>(LinearLayout.java:248)
    at android.widget.LinearLayout.<init>(LinearLayout.java:244)
    at android.widget.LinearLayout.<init>(LinearLayout.java:240)
    ... 35 more
android.view.InflateException: Binary XML file line #13: Binary XML file line #2: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at android.view.LayoutInflater.createView(LayoutInflater.java:658)
    at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64)
    at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:105)
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:731)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:799)
    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:976)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
    at cn.com.zwwl.bayuwen.activity.MainActivity.onCreate(MainActivity.java:137)
    at android.app.Activity.performCreate(Activity.java:7436)
    at android.app.Activity.performCreate(Activity.java:7426)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
    at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5380)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5276)
    at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
    at android.os.Handler.dispatchMessage(Handler.java:109)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:7470)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 16 to dimension: type=0x1
    at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:783)
    at android.view.View.<init>(View.java:5068)
    at android.view.ViewGroup.<init>(ViewGroup.java:659)
    at android.widget.LinearLayout.<init>(LinearLayout.java:248)
    at android.widget.LinearLayout.<init>(LinearLayout.java:244)
    at android.widget.LinearLayout.<init>(LinearLayout.java:240)
    ... 35 more
android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at android.view.LayoutInflater.createView(LayoutInflater.java:658)
    at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64)
    at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:105)
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:731)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:799)
    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:976)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
    at cn.com.zwwl.bayuwen.activity.MainActivity.onCreate(MainActivity.java:137)
    at android.app.Activity.performCreate(Activity.java:7436)
    at android.app.Activity.performCreate(Activity.java:7426)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
    at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5380)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5276)
    at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
    at android.os.Handler.dispatchMessage(Handler.java:109)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:7470)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 16 to dimension: type=0x1
    at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:783)
    at android.view.View.<init>(View.java:5068)
    at android.view.ViewGroup.<init>(ViewGroup.java:659)
    at android.widget.LinearLayout.<init>(LinearLayout.java:248)
    at android.widget.LinearLayout.<init>(LinearLayout.java:244)
    at android.widget.LinearLayout.<init>(LinearLayout.java:240)
    ... 35 more
java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at android.view.LayoutInflater.createView(LayoutInflater.java:658)
    at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64)
    at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:105)
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:731)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:799)
    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:976)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
    at cn.com.zwwl.bayuwen.activity.MainActivity.onCreate(MainActivity.java:137)
    at android.app.Activity.performCreate(Activity.java:7436)
    at android.app.Activity.performCreate(Activity.java:7426)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
    at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5380)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5276)
    at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
    at android.os.Handler.dispatchMessage(Handler.java:109)
    at android.os.Looper.loop(Looper.java:207)
    at android.app.ActivityThread.main(ActivityThread.java:7470)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 16 to dimension: type=0x1
    at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:783)
    at android.view.View.<init>(View.java:5068)
    at android.view.ViewGroup.<init>(ViewGroup.java:659)
    at android.widget.LinearLayout.<init>(LinearLayout.java:248)
    at android.widget.LinearLayout.<init>(LinearLayout.java:244)
    at android.widget.LinearLayout.<init>(LinearLayout.java:240)
    ... 35 more
java.lang.UnsupportedOperationException: Can't convert value at index 16 to dimension: type=0x1
    at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:783)
    at android.view.View.<init>(View.java:5068)
    at android.view.ViewGroup.<init>(ViewGroup.java:659)
    at android.widget.LinearLayout.<init>(LinearLayout.java:248)
    at android.widget.LinearLayout.<init>(LinearLayout.java:244)
    at android.widget.LinearLayout.<init>(LinearLayout.java:240)
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at android.view.LayoutInflater.createView(LayoutInflater.java:658)
    at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:64)
    at 友盟统计的崩溃里面的报错，但是我看那机型，我有建和他匹配的dpi
（Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 16 to dimension: type=0x1）为什么还报这个呢？

**Comment by cervy** [comment]
看xml文件

**Comment by TopTime1** [comment]
看了就是引用dimens里的东西

**Comment by ladingwu** [comment]
问题是出在你的xml文件中，但是具体是什么问题看不出来，你确认下两点：1，默认的dimens文件夹下，都有默认的尺寸引用吧 2，该xml文件中，对应的出错尺寸引用代码引用是否有问题
